config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tickets
  resources :routes
  resources :trains
  resources :railway_stations
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  # has_and_belongs_to_many :routes
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, foreign_key: :current_station_id

  validates :title, presence: true
end

app/models/railway_station_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  # has_and_belongs_to_many :railway_stations
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user
  belongs_to :from_station, class_name: 'RailwayStation'
  belongs_to :to_station, class_name: 'RailwayStation'

  validates :number, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :tickets
  belongs_to :route
  belongs_to :current_station,
             class_name: 'RailwayStation',
             foreign_key: :current_station_id

  validates :number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/railway_stations_controller.rb
# frozen_string_literal: true

class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[show edit update destroy]

  # GET /railway_stations
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  def show; end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit; end

  # POST /railway_stations
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station, notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /railway_stations/1
  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station, notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /railway_stations/1
  def destroy
    @railway_station.destroy
    redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/controllers/routes_controller.rb
# frozen_string_literal: true

class RoutesController < ApplicationController
  before_action :set_route, only: %i[show edit update destroy]

  # GET /routes
  def index
    @routes = Route.all
  end

  # GET /routes/1
  def show; end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit; end

  # POST /routes
  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route, notice: 'Route was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /routes/1
  def update
    if @route.update(route_params)
      redirect_to @route, notice: 'Route was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /routes/1
  def destroy
    @route.destroy
    redirect_to routes_url, notice: 'Route was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_route
    @route = Route.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]

  # GET /tickets
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  def show; end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit; end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:number)
  end
end

app/controllers/trains_controller.rb
# frozen_string_literal: true

class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains
  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def train_params
    params.require(:train).permit(:number, :current_station_id, :route)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/railway_stations/#show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Станция не входит ни в один маршрут</p>
<% else %>
  <p>Станция входит в следующие маршруты:</p>
  <ul>
    <% @railway_station.routes.each do |route| %>
      <li><%= route.name %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/_form.html.erb
<%= form_with(model: railway_station, local: true) do |f| %>
<%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :railway_station_title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= link_to "#{railway_station.title}", railway_station %></td>
  <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Станция не входит ни в один маршрут</p>
<% else %>
  <p>Станция входит в следующие маршруты:</p>
  <ul>
    <% @railway_station.routes.each do |route| %>
      <li><%= route.name %></li>
    <% end %>
  </ul>
<% end %>


<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.slim
p#notice
  = notice
p
  strong'
    | Title:
  = @railway_station.title
- if @railway_station.routes.empty?
  p
    | Станция не входит ни в один маршрут
- else
  p
    | Станция входит в следующие маршруты:
  ul
    - @railway_station.routes.each do |route|
      li
        = link_to "#{route.name}", route
= link_to 'Edit', edit_railway_station_path(@railway_station)
|  |
= link_to 'Back', railway_stations_path

app/views/routes/#show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Наименование:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Станции в маршруте:</strong>
</p>

<p>
  <% if @route.railway_stations.empty? %>
    Нет станций в маршруте
  <% else %>
  <ul>
    <% @route.railway_stations.each do |station| %>
      <li><%= station.title %></li>
    <% end %>
  </ul>
<% end %>
</p>

<p>
  <strong>Поезда на маршруте:</strong>
</p>

<p>
  <% if @route.trains.empty? %>
    Нет поездов на маршруте
  <% else %>
  <ul>
    <% @route.trains.each do |train| %>
      <li><%= train.number %></li>
    <% end %>
  </ul>
<% end %>
</p>

<%= link_to 'Редактировать', edit_route_path(@route) %> |
<%= link_to 'Назад', routes_path %>

app/views/routes/_form.html.erb
<%= form_with(model: @route, local: true) do |f| %>
  <%= render 'common/errors', resource: @route %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :route_name %>
  </div>

  <div class="field">
    <%= f.label :railway_station_ids, 'Станции в маршруте' %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<tr>
  <td><%= link_to "#{route.name}", route %></td>
  <td><%= link_to 'Edit', edit_route_path(route) %></td>
  <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @routes %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.slim
p#notice
  = notice
p
  strong'
    | Name
  = @route.name
p
  strong'
    | Station in the route:
p
  - if @route.railway_stations.empty?
    |  No station on the route
  - else
    ul
      - @route.railway_stations.each do |station|
        li
          = link_to "#{station.title}", station
p
  strong'
    | Trains on the route:
p
  - if @route.trains.empty?
    |  No trains on the route
  - else
    ul
      - @route.trains.each do |train|
        li
          = link_to "#{train.number}", train
= link_to 'Edit', edit_route_path(@route)
|  |&nbsp
= link_to 'Back', routes_path

app/views/tickets/_form.html.slim
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - @ticket.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :number
    = f.text_field :number
  .actions = f.submit

app/views/tickets/_ticket.html.slim
tr
  td = link_to "#{ticket.number}", ticket
  td = link_to 'Edit', edit_ticket_path(ticket)
  td = link_to 'Destroy', ticket, data: { confirm: 'Are you sure?' }, method: :delete

app/views/tickets/edit.html.slim
h1 Editing ticket

== render 'form'

=> link_to 'Show', @ticket
'|
=< link_to 'Back', tickets_path

app/views/tickets/index.html.slim
p#notice
  = notice
h1
  | Tickets
table
  thead
    tr
      th Number
  tbody
    = render @tickets
br
= link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.slim
h1 New ticket

== render 'form'

= link_to 'Back', tickets_path

app/views/tickets/show.html.slim
p#notice = notice

p
  strong' Number:
  = @ticket.number

=> link_to 'Edit', edit_ticket_path(@ticket)
'|
=< link_to 'Back', tickets_path

app/views/trains/#new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/_form.html.erb
<%= form_with(model: @train, local: true) do |f| %>
<%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number, id: :train_number %>
  </div>

  <div class="field">
    <%= f.label :current_station_id, 'Текущая станция' %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <br>
  <br>
  <div class="field">
    <%= f.label :route_id, 'Текущий маршрут' %>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>
  <br>
  <br>
    <div class="actions">
      <%= f.submit "#{ @train.new_record? ? 'Создать' : 'Изменить' }" %>
    </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= link_to "#{train.number}", train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/new.html.slim
h1
  | New Train
= render 'form', train: @train
= link_to 'Back', trains_path

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= link_to "#{@train.number}", @train%>
  <br>
  <br>
  <strong>Current station:</strong>
  <%= link_to "#{@train.current_station.title}", @train.current_station %>
  <br>
  <br>
  <strong>Train route:</strong>
  <%= link_to "#{@train.route.name}", @train.route %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/users/_user.html.slim
tr
  td = link_to "#{user.name}", user
  td = link_to 'Edit', edit_user_path(user)
  td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
  tbody
    = render @users
br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong' Name:
  = @user.name
  / = link_to @user.name, edit_user_path(@user)

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path

app/views/welcome/index.html.erb
<h1>Railway Welcome</h1>

<%#= JUST FOR TEST %>
<%#= link_to 'Stations list', railway_stations_path %>

<!--<br>-->
<!--<br>-->
<!--<a href="/railway_stations">Stations list</a>-->
<!--<br>-->
<!--<br>-->

<%#= link_to 'first station', railway_station_path(1) %>

<div>
  <ul>
    <li><%= link_to "Stations list", railway_stations_path %></li>
    <br>
    <li><%= link_to "Routes list", routes_path %></li>
    <br>
    <li><%= link_to "Trains list", trains_path %></li>
    <br>
    <li><%= link_to "Users list", users_path %></li>
    <br>
    <li><%= link_to "Tickets list", tickets_path %></li>
  </ul>
</div>